### ISSUE TITLE
Error on executing example code

### ISSUE THREAD

**Issue by ShahimEssaid** [ShahimEssaid/owltools#73]
_From [daniele1...@hotmail.com](https://code.google.com/u/107453739665095522476/) on July 11, 2013 07:51:51_

\<b>What steps will reproduce the problem?</b>
1.Compile&#13;
2.Run&#13;
&#13;
&#13;
\<b>What is the expected output? What do you see instead?</b>
 I receive this error:&#13;
&#13;
Excecute the query:&#13;
Exception in thread "main" java.lang.NoClassDefFoundError: jpaul/DataStructs/UnionFind&#13;
SELECT * WHERE {&#13;
Type(?x, &lt;<a href="http://www.w3.org/TR/2003/PR-owl-guide-20031209/wine#WhiteWine&gt;)" rel="nofollow">http://www.w3.org/TR/2003/PR-owl-guide-20031209/wine#WhiteWine&gt;)</a>}&#13;
-------------------------------------------------&#13;
	at de.derivo.sparqldlapi.impl.QueryEngineImpl.findComponents(Unknown Source)&#13;
	at de.derivo.sparqldlapi.impl.QueryEngineImpl.execute(Unknown Source)&#13;
	at javaapplication6.SparqlDLQueryTest.processQuery(SparqlDLQueryTest.java:167)&#13;
	at javaapplication6.SparqlDLQueryTest.testQuery(SparqlDLQueryTest.java:69)&#13;
	at javaapplication6.JavaApplication6.main(JavaApplication6.java:19)&#13;
Caused by: java.lang.ClassNotFoundException: jpaul.DataStructs.UnionFind&#13;
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)&#13;
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)&#13;
	at java.security.AccessController.doPrivileged(Native Method)&#13;
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)&#13;
	at java.lang.ClassLoader.loadClass(ClassLoader.java:423)&#13;
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)&#13;
	at java.lang.ClassLoader.loadClass(ClassLoader.java:356)&#13;
	... 5 more&#13;
Java Result: 1&#13;
&#13;
\<b>What version of the product are you using? On what operating system?</b>
OWLAPI 3.4.3&#13;
&#13;

_Original issue: http://code.google.com/p/owltools/issues/detail?id=73_

**Comment by ShahimEssaid** [comment]
_From [HDie...@lbl.gov](https://code.google.com/u/115902121950964170841/) on July 11, 2013 14:59:41_

Hello,
I assume with the example you mean the test class: owltools.graph.SparqlDLQueryTest in OWLTools-Core.
This test case runs without any problems. Judging from your error message, you created new test example in a different project. That project seems not to import all the required jar files. In your case, you are missing the jpaul.jar file.
We handle all of our imports via Maven and its pom.xml project descriptor. JPaul and JDom are both transitive dependencies for the sparqldl-api.

**Comment by ShahimEssaid** [comment]
_From [daniele1...@hotmail.com](https://code.google.com/u/107453739665095522476/) on July 12, 2013 00:57:24_

Yes, strangely I've downloaded only sparqldl-api.jar file without dependencies. Thank you !!

**Comment by ShahimEssaid** [comment]
_From [HDie...@lbl.gov](https://code.google.com/u/115902121950964170841/) on July 29, 2013 10:17:41_

**Status:** Done
