### ISSUE TITLE
junit test fails for MolecularModeServer

### ISSUE THREAD

**Issue by ShahimEssaid** [ShahimEssaid/owltools#97]
_From [mcour...@gmail.com](https://code.google.com/u/116795168307825520406/) on May 29, 2014 16:52:58_

\<b>What steps will reproduce the problem?</b>
I was trying to install owl tools and running mvm clean package&#13;
&#13;
\<b>What is the expected output? What do you see instead?</b>
&#13;
I see&#13;
&#13;
Results :&#13;
&#13;
Failed tests:   testModelAnnotations(owltools.gaf.lego.server.handler.BatchModelHandlerTest): expected:&lt;2&gt; but was:&lt;3&gt;&#13;
&#13;
Tests run: 11, Failures: 1, Errors: 0, Skipped: 0&#13;
&#13;
[INFO] ------------------------------------------------------------------------&#13;
[INFO] Reactor Summary:&#13;
[INFO] &#13;
[INFO] OWLTools-Parent ................................... SUCCESS [ 21.475 s]&#13;
[INFO] OWLTools-Core ..................................... SUCCESS [05:43 min]&#13;
[INFO] Lego .............................................. SUCCESS [  4.713 s]&#13;
[INFO] OWLTools-Annotation ............................... SUCCESS [01:30 min]&#13;
[INFO] OWLTools-Oort ..................................... SUCCESS [ 18.337 s]&#13;
[INFO] OWLTools-Sim ...................................... SUCCESS [ 34.007 s]&#13;
[INFO] OWLTools-Web ...................................... SUCCESS [  8.819 s]&#13;
[INFO] OWLTools-Solr ..................................... SUCCESS [ 10.176 s]&#13;
[INFO] OWLTools-Runner ................................... SUCCESS [01:22 min]&#13;
[INFO] OWLTools-NCBI ..................................... SUCCESS [  4.081 s]&#13;
[INFO] MolecularModelServer .............................. FAILURE [03:42 min]&#13;
[INFO] ------------------------------------------------------------------------&#13;
[INFO] BUILD FAILURE&#13;
[INFO] ------------------------------------------------------------------------&#13;
[INFO] Total time: 14:00 min&#13;
[INFO] Finished at: 2014-05-29T16:46:52-08:00&#13;
[INFO] Final Memory: 27M/95M&#13;
[INFO] ------------------------------------------------------------------------&#13;
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.2:test (default-test) on project MolecularModelServer: There are test failures.&#13;
[ERROR] &#13;
[ERROR] Please refer to /Users/mcourtot/Desktop/projects/owltools/MolecularModelServer/target/surefire-reports for the individual test results.&#13;
[ERROR] -&gt; [Help 1]&#13;
[ERROR] &#13;
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.&#13;
[ERROR] Re-run Maven using the -X switch to enable full debug logging.&#13;
[ERROR] &#13;
[ERROR] For more information about the errors and possible solutions, please read the following articles:&#13;
[ERROR] [Help 1] \<a href="http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException" rel="nofollow">http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException</a>&#13;
[ERROR] &#13;
[ERROR] After correcting the problems, you can resume the build with the command&#13;
[ERROR]   mvn &lt;goals&gt; -rf :MolecularModelServer&#13;
&#13;
\<b>What version of the product are you using? On what operating system?</b>
OS 10.9.2&#13;
&#13;
\<b>Please provide any additional information below.</b>
Log reads:&#13;
&#13;
-------------------------------------------------------------------------------&#13;
Test set: owltools.gaf.lego.server.handler.BatchModelHandlerTest&#13;
-------------------------------------------------------------------------------&#13;
Tests run: 11, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 200.593 sec &lt;&lt;&lt; FAILURE!&#13;
testModelAnnotations(owltools.gaf.lego.server.handler.BatchModelHandlerTest)  Time elapsed: 5.729 sec  &lt;&lt;&lt; FAILURE!&#13;
java.lang.AssertionError: expected:&lt;2&gt; but was:&lt;3&gt;&#13;
	at org.junit.Assert.fail(Assert.java:88)&#13;
	at org.junit.Assert.failNotEquals(Assert.java:743)&#13;
	at org.junit.Assert.assertEquals(Assert.java:118)&#13;
	at org.junit.Assert.assertEquals(Assert.java:555)&#13;
	at org.junit.Assert.assertEquals(Assert.java:542)&#13;
	at owltools.gaf.lego.server.handler.BatchModelHandlerTest.testModelAnnotations(BatchModelHandlerTest.java:245)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)&#13;
	at java.lang.reflect.Method.invoke(Method.java:597)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)&#13;
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)&#13;
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)&#13;
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)&#13;
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)&#13;
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)&#13;
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)&#13;
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)&#13;
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)&#13;
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)&#13;
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)&#13;
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)&#13;
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)&#13;
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)&#13;
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)&#13;
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)&#13;
	at java.lang.reflect.Method.invoke(Method.java:597)&#13;
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)&#13;
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)&#13;
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)&#13;
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:113)&#13;
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

_Original issue: http://code.google.com/p/owltools/issues/detail?id=97_

**Comment by ShahimEssaid** [comment]
_From [HDie...@lbl.gov](https://code.google.com/u/115902121950964170841/) on May 29, 2014 17:03:58_

Thank you for reporting the issue. A fix for the problem has been committed in revision r2221 .

**Status:** Fixed
